services:
  - type: web
    name: uqari-pms-client
    runtime: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://uqari-pms-api.onrender.com/api
